<?php

namespace tests;

use App\Bowling;
use PHPUnit\Framework\TestCase;

/**
 * @property Bowling $bowling
 */
class BowlingTest extends TestCase
{
    private Bowling $bowling;

    public function test_all_missing()
    {
        $this->scoreShouldBe(0);

    }

    public function test_all_single_pins()
    {
        $this->bowling->rollMany(20, 1);
        $this->scoreShouldBe(20);

    }

    public function test_all_strike()
    {
        $this->bowling->rollMany(12, 10);
        $this->scoreShouldBe(300);

    }

    /**
     * @return void
     */
    public function scoreShouldBe($expected): void
    {
        self::assertEquals($expected, $this->bowling->score());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bowling = new Bowling();
    }
}
