<?php

namespace tests;

use App\Bowling;
use PHPUnit\Framework\TestCase;

/**
 * @property Bowling $bowling
 */
class BowlingTest extends TestCase
{
    private Bowling $bowling;

    public function test_all_miss()
    {
        $this->scoreShouldBe(0);
    }

    public function test_all_single_point()
    {
        $this->bowling->rollMany(20, 3);
        $this->scoreShouldBe(60);
    }

    /**
     * @return void
     */
    public function scoreShouldBe($expected): void
    {
        self::assertEquals($expected, $this->bowling->score());
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->bowling = new Bowling();

    }
}
